version: '3.7'

services:
  php:
    build: .
    volumes:
      - ../site/:/var/www/site/
    depends_on:
      - postgres
    restart: always

  nginx:
    image: nginx:1.17
    ports:
      - "8081:80"
    volumes:
      - ../site/:/var/www/site/
      - ./cfg/nginx/:/etc/nginx/conf.d/
    depends_on:
      - php
    restart: always

  postgres:
    image: postgres:12
    volumes:
      - ../site/:/var/www/site/
      - db_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: aloe
      POSTGRES_USER: aloe
      POSTGRES_DB: aloe

volumes:
  db_data:

